name: 'logistics_analytics'
version: '1.0.0'
config-version: 2

profile: 'logistics_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Environment-specific variables
vars:
  # Global variables
  start_date: '2023-01-01'
  rolling_7d: 7
  rolling_30d: 30
  rolling_90d: 90
  data_freshness_hours: 6
  critical_freshness_hours: 2
  
  # Database and schema variables
  raw_database: 'LOGISTICS_DW_PROD'
  staging_database: 'LOGISTICS_DW_PROD'
  marts_database: 'LOGISTICS_DW_PROD'
  analytics_database: 'LOGISTICS_DW_PROD'
  
  # Development environment
  dev:
    start_date: '2023-01-01'
    test_store_failures: true
    refresh_incremental: false
    max_partition_days: 30
    enable_real_time_features: false
    
  # Staging environment  
  staging:
    start_date: '2022-01-01'
    test_store_failures: true
    refresh_incremental: true
    max_partition_days: 90
    enable_real_time_features: true
    
  # Production environment
  prod:
    start_date: '2021-01-01'
    test_store_failures: false
    refresh_incremental: true
    max_partition_days: 365
    enable_real_time_features: true

# Environment-specific model configurations
models:
  logistics_analytics:
    +materialized: view
    +persist_docs:
      relation: true
      columns: true
    
    staging:
      +materialized: view
      +on_schema_change: "sync_all_columns"
      dev:
        +materialized: ephemeral
        
    marts:
      +materialized: table
      +on_schema_change: "sync_all_columns"
      
      dimensions:
        +materialized: table
        dev:
          +materialized: view
        prod:
          +post-hook: "{{ log_table_stats(this) }}"
          
      facts:
        +materialized: incremental
        +unique_key: 'shipment_id'
        +on_schema_change: "sync_all_columns"
        dev:
          +materialized: table
          +full_refresh: true
        prod:
          +post-hook: 
            - "{{ optimize_clustering(this) }}"
            - "{{ log_table_stats(this) }}"
            
      analytics:
        +materialized: view
        prod:
          +post-hook: "{{ refresh_materialized_view(this) }}"
          
      ml_features:
        +materialized: table
        +tags: ["ml", "features"]
        dev:
          +materialized: view
        prod:
          +post-hook: "{{ update_feature_store_metadata(this) }}"

# Environment-specific seeds
seeds:
  logistics_analytics:
    +quote_columns: false
    dev:
      +enabled: true
    staging:
      +enabled: true  
    prod:
      +enabled: false

# Environment-specific tests
tests:
  logistics_analytics:
    +store_failures: "{{ var('test_store_failures', true) }}"
    +severity: warn
    prod:
      +severity: error

# Environment-specific snapshots
snapshots:
  logistics_analytics:
    +target_schema: snapshots
    +strategy: timestamp
    +updated_at: updated_at
    dev:
      +enabled: false
    prod:
      +enabled: true


dispatch:
  - macro_namespace: dbt_utils
    search_order: ["smart_logistics", "dbt_utils"]
