name: smart_logistics
version: 1.0.0
config-version: 2

profile: smart_logistics

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  smart_logistics:
    +materialized: table
    staging:
      +materialized: view
      +tags: ["staging"]
    marts:
      +materialized: table
      +tags: ["marts"]
      analytics:
        +materialized: table
        +tags: ["ml", "analytics"]
      dimensions:
        +materialized: table
        +tags: ["dim"]
      facts:
        +materialized: table
        +tags: ["fact"]
      ml_features:
        +materialized: table
        +tags: ["ml", "features"]
      business_intelligence:
        +materialized: view
        +tags: ["bi", "dashboard"]
      monitoring:
        +materialized: view
        +tags: ["monitoring", "quality"]

snapshots:
  smart_logistics:
    +target_schema: snapshots
    +strategy: timestamp
    +updated_at: updated_at

tests:
  +store_failures: true
  +severity: error

vars:
  start_date: 2023-01-01
  rolling_7d: 7
  rolling_30d: 30
  rolling_90d: 90
  data_freshness_hours: 6
  critical_freshness_hours: 2

dispatch:
  - macro_namespace: dbt_utils
    search_order: ["smart_logistics", "dbt_utils"]
