name: 'smart_logistics'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'smart_logistics'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  smart_logistics:
    +materialized: table
    staging:
      +materialized: view
      +tags: ["staging"]
    marts:
      +materialized: table
      +tags: ["marts"]
    analytics:
      ml_features:
        +materialized: table
        +tags: ["ml", "features"]
      rolling_analytics:
        +materialized: table
        +tags: ["analytics", "rolling"]
      business_intelligence:
        +materialized: view
        +tags: ["bi", "dashboard"]
      monitoring:
        +materialized: view
        +tags: ["monitoring", "quality"]

# Snapshot configurations
snapshots:
  smart_logistics:
    +target_schema: snapshots
    +strategy: timestamp
    +updated_at: updated_at

# Test configurations
tests:
  +store_failures: true
  +severity: error

# Variables
vars:
  # Date range for incremental models
  start_date: '2023-01-01'
  # Number of days for rolling calculations
  rolling_7d: 7
  rolling_30d: 30
  rolling_90d: 90
  # Freshness thresholds
  data_freshness_hours: 6
  critical_freshness_hours: 2

# Macros
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['smart_logistics', 'dbt_utils']

# Package dependencies
packages:
  - package: dbt-labs/dbt_utils
    version: 1.1.1
  - package: calogica/dbt_expectations
    version: 0.10.1