logistics_analytics:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SF_ACCOUNT') }}"
      user: "{{ env_var('SF_USER') }}"
      password: "{{ env_var('SF_PASSWORD') }}"
      role: "{{ env_var('SF_ROLE', 'DBT_DEV_ROLE') }}"
      database: LOGISTICS_DW_DEV
      warehouse: COMPUTE_WH_XS
      schema: ANALYTICS
      threads: 4
      keepalive: false
      query_tag: dbt_dev

    staging:
      type: snowflake
      account: "{{ env_var('SF_ACCOUNT') }}"
      user: "{{ env_var('SF_USER') }}"
      password: "{{ env_var('SF_PASSWORD') }}"
      role: "{{ env_var('SF_ROLE', 'DBT_STAGING_ROLE') }}"
      database: LOGISTICS_DW_STAGING
      warehouse: COMPUTE_WH_SMALL
      schema: ANALYTICS
      threads: 8
      keepalive: false
      query_tag: dbt_staging

    prod:
      type: snowflake
      account: "{{ env_var('SF_ACCOUNT') }}"
      user: "{{ env_var('SF_USER') }}"
      password: "{{ env_var('SF_PASSWORD') }}"
      role: "{{ env_var('SF_ROLE', 'DBT_PROD_ROLE') }}"
      database: LOGISTICS_DW_PROD
      warehouse: COMPUTE_WH_MEDIUM
      schema: ANALYTICS
      threads: 12
      keepalive: false
      query_tag: dbt_prod