smart_logistics:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SF_ACCOUNT') }}"
      user: "{{ env_var('SF_USER') }}"
      password: "{{ env_var('SF_PASSWORD') }}"
      role: "{{ env_var('SF_ROLE', 'TRANSFORMER') }}"
      database: "{{ env_var('SF_DATABASE', 'LOGISTICS_DW') }}"
      warehouse: "{{ env_var('SF_WAREHOUSE', 'TRANSFORMING') }}"
      schema: "{{ env_var('SF_SCHEMA', 'DBT_DEV') }}"
      threads: 8
      client_session_keep_alive: true
