logistics_analytics:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SF_ACCOUNT') }}"
      user: "{{ env_var('SF_USER') }}"
      password: "{{ env_var('SF_PASSWORD') }}"
      role: "{{ env_var('SF_ROLE', 'DBT_DEV_ROLE') }}"
      database: "{{ env_var('SF_DATABASE', 'LOGISTICS_DW_DEV') }}"
      warehouse: "{{ env_var('SF_WAREHOUSE', 'COMPUTE_WH_XS') }}"
      schema: "{{ env_var('SF_SCHEMA', 'ANALYTICS') }}"
      threads: "{{ env_var('DBT_THREADS', 4) | int }}"
      keepalive: false
      query_tag: dbt_dev

    staging:
      type: snowflake
      account: "{{ env_var('SF_ACCOUNT') }}"
      user: "{{ env_var('SF_USER') }}"
      password: "{{ env_var('SF_PASSWORD') }}"
      role: "{{ env_var('SF_ROLE', 'DBT_STAGING_ROLE') }}"
      database: "{{ env_var('SF_DATABASE', 'LOGISTICS_DW_DEV') }}"
      warehouse: "{{ env_var('SF_WAREHOUSE', 'COMPUTE_WH_SMALL') }}"
      schema: "{{ env_var('SF_SCHEMA', 'ANALYTICS') }}"
      threads: "{{ env_var('DBT_THREADS', '8') }}"
      keepalive: false
      query_tag: dbt_staging

    prod:
      type: snowflake
      account: "{{ env_var('SF_ACCOUNT') }}"
      user: "{{ env_var('SF_USER') }}"
      password: "{{ env_var('SF_PASSWORD') }}"
      role: "{{ env_var('SF_ROLE', 'DBT_PROD_ROLE') }}"
      database: "{{ env_var('SF_DATABASE', 'LOGISTICS_DW_DEV') }}"
      warehouse: "{{ env_var('SF_WAREHOUSE', 'COMPUTE_WH_MEDIUM') }}"
      schema: "{{ env_var('SF_SCHEMA', 'ANALYTICS') }}"
      threads: "{{ env_var('DBT_THREADS', '12') }}"
      keepalive: false
      query_tag: dbt_prod

    ci:
      type: snowflake
      account: "{{ env_var('SF_ACCOUNT') }}"
      user: "{{ env_var('SF_USER') }}"
      password: "{{ env_var('SF_PASSWORD') }}"
      role: "{{ env_var('SF_ROLE', 'DBT_DEV_ROLE') }}"
      database: "{{ env_var('SF_DATABASE', 'LOGISTICS_DW_DEV') }}"
      warehouse: "{{ env_var('SF_WAREHOUSE', 'COMPUTE_WH_XS') }}"
      schema: "{{ env_var('SF_SCHEMA', 'ANALYTICS') }}"
      threads: "{{ env_var('DBT_THREADS', '2') }}"
      keepalive: false
      query_tag: dbt_ci