-- =====================================================
-- Consolidated Rolling Analytics View
-- Combines customer, operational, route, and maintenance rolling analytics
-- References dbt models as single source of truth
-- =====================================================

CREATE OR REPLACE VIEW LOGISTICS_DW_PROD.ANALYTICS.V_ROLLING_ANALYTICS AS

-- Customer rolling analytics
SELECT 
    'customer' AS entity_type,
    customer_id AS entity_id,
    shipment_date AS feature_date,
    customer_name,
    volume_segment,
    customer_type,
    
    -- Current day metrics
    daily_shipments,
    daily_weight,
    daily_volume,
    daily_revenue,
    daily_avg_rating,
    daily_on_time_rate,
    
    -- Rolling metrics
    shipments_30d_avg,
    revenue_30d_avg,
    weight_30d_avg,
    shipments_30d_total,
    revenue_30d_total,
    
    -- Year-over-year comparison
    shipments_same_day_last_year,
    revenue_same_day_last_year,
    revenue_yoy_growth_percent,
    
    -- Trend indicators
    shipments_7d_avg,
    shipments_90d_avg,
    activity_ratio_7d_vs_90d,
    volume_trend_7d_vs_30d,
    revenue_trend_30d_vs_90d,
    
    -- Customer lifecycle indicators
    days_since_first_order,
    days_to_last_order,
    
    -- Behavior consistency
    shipment_volatility_30d,
    behavior_consistency,
    
    -- Null fields for other entity types
    NULL AS vehicle_type,
    NULL AS origin_city,
    NULL AS daily_deliveries,
    NULL AS daily_distance_km,
    NULL AS daily_fuel_cost,
    NULL AS daily_delivery_cost,
    NULL AS daily_avg_speed_kmh,
    NULL AS daily_fuel_cost_per_km,
    NULL AS daily_profit,
    NULL AS deliveries_7d_avg,
    NULL AS distance_7d_avg,
    NULL AS on_time_rate_7d_avg,
    NULL AS rating_7d_avg,
    NULL AS fuel_efficiency_7d_avg,
    NULL AS deliveries_30d_avg,
    NULL AS distance_30d_avg,
    NULL AS on_time_rate_30d_avg,
    NULL AS rating_30d_avg,
    NULL AS fuel_efficiency_30d_avg,
    NULL AS deliveries_90d_avg,
    NULL AS distance_90d_avg,
    NULL AS on_time_rate_90d_avg,
    NULL AS rating_90d_avg,
    NULL AS fuel_efficiency_90d_avg,
    NULL AS on_time_volatility_30d,
    NULL AS fuel_efficiency_volatility_30d,
    NULL AS performance_trend_7d_vs_30d,
    NULL AS fuel_efficiency_trend_7d_vs_30d,
    NULL AS route_name,
    NULL AS route_type,
    NULL AS haul_type,
    NULL AS daily_trips,
    NULL AS avg_actual_duration,
    NULL AS avg_planned_duration,
    NULL AS avg_duration_ratio,
    NULL AS avg_customer_satisfaction,
    NULL AS total_fuel_cost,
    NULL AS total_revenue,
    NULL AS avg_fuel_cost_per_km,
    NULL AS severe_delays,
    NULL AS poor_ratings,
    NULL AS on_time_rate_7d_avg AS route_on_time_rate_7d_avg,
    NULL AS duration_ratio_7d_avg,
    NULL AS satisfaction_7d_avg,
    NULL AS fuel_efficiency_7d_avg AS route_fuel_efficiency_7d_avg,
    NULL AS on_time_rate_30d_avg AS route_on_time_rate_30d_avg,
    NULL AS duration_ratio_30d_avg,
    NULL AS satisfaction_30d_avg,
    NULL AS on_time_rate_90d_avg AS route_on_time_rate_90d_avg,
    NULL AS duration_ratio_90d_avg,
    NULL AS satisfaction_90d_avg,
    NULL AS on_time_volatility_30d AS route_on_time_volatility_30d,
    NULL AS duration_volatility_30d,
    NULL AS route_performance_rating,
    NULL AS route_risk_level,
    NULL AS make,
    NULL AS model,
    NULL AS model_year,
    NULL AS current_mileage,
    NULL AS maintenance_interval_miles,
    NULL AS last_maintenance_date,
    NULL AS next_maintenance_date,
    NULL AS avg_engine_temp,
    NULL AS avg_fuel_level,
    NULL AS avg_engine_rpm,
    NULL AS total_harsh_braking,
    NULL AS total_harsh_acceleration,
    NULL AS total_speeding_events,
    NULL AS avg_idle_time,
    NULL AS avg_engine_health,
    NULL AS max_engine_temp,
    NULL AS avg_fuel_consumption,
    NULL AS daily_maintenance_alerts,
    NULL AS unique_diagnostic_codes,
    NULL AS maintenance_events_7d,
    NULL AS maintenance_cost_7d,
    NULL AS maintenance_events_30d,
    NULL AS maintenance_cost_30d,
    NULL AS maintenance_events_90d,
    NULL AS maintenance_cost_90d,
    NULL AS maintenance_urgency,
    NULL AS days_since_last_maintenance,
    NULL AS miles_since_last_maintenance,
    NULL AS last_service_interval_days,
    NULL AS avg_engine_temp_7d,
    NULL AS avg_engine_health_7d,
    NULL AS harsh_braking_7d,
    NULL AS harsh_acceleration_7d,
    NULL AS maintenance_alerts_7d,
    NULL AS engine_health_14d_avg,
    NULL AS max_engine_temp_14d_avg,
    NULL AS avg_engine_temp_30d,
    NULL AS avg_engine_health_30d,
    NULL AS harsh_braking_30d,
    NULL AS harsh_acceleration_30d,
    NULL AS maintenance_alerts_30d,
    NULL AS avg_engine_health_90d,
    NULL AS harsh_braking_90d,
    NULL AS maintenance_alerts_90d,
    NULL AS engine_health_trend,
    NULL AS service_recommendation,
    NULL AS predictive_maintenance_score,
    NULL AS maintenance_risk_score,
    NULL AS next_maintenance_due_days

FROM LOGISTICS_DW_PROD.MARTS.ML_ROLLING_ANALYTICS
WHERE entity_type = 'customer'
    AND feature_date >= DATEADD('day', -90, CURRENT_DATE())

UNION ALL

-- Vehicle rolling analytics
SELECT 
    'vehicle' AS entity_type,
    entity_id,
    feature_date,
    NULL AS customer_name,
    NULL AS volume_segment,
    NULL AS customer_type,
    NULL AS daily_shipments,
    NULL AS daily_weight,
    NULL AS daily_volume,
    NULL AS daily_revenue,
    NULL AS daily_avg_rating,
    NULL AS daily_on_time_rate,
    NULL AS shipments_30d_avg,
    NULL AS revenue_30d_avg,
    NULL AS weight_30d_avg,
    NULL AS shipments_30d_total,
    NULL AS revenue_30d_total,
    NULL AS shipments_same_day_last_year,
    NULL AS revenue_same_day_last_year,
    NULL AS revenue_yoy_growth_percent,
    NULL AS shipments_7d_avg,
    NULL AS shipments_90d_avg,
    NULL AS activity_ratio_7d_vs_90d,
    NULL AS volume_trend_7d_vs_30d,
    NULL AS revenue_trend_30d_vs_90d,
    NULL AS days_since_first_order,
    NULL AS days_to_last_order,
    NULL AS shipment_volatility_30d,
    NULL AS behavior_consistency,
    vehicle_type,
    origin_city,
    daily_deliveries,
    daily_distance_km,
    daily_fuel_cost,
    daily_delivery_cost,
    daily_avg_speed_kmh,
    daily_fuel_cost_per_km,
    daily_profit,
    deliveries_7d_avg,
    distance_7d_avg,
    on_time_rate_7d_avg,
    rating_7d_avg,
    fuel_efficiency_7d_avg,
    deliveries_30d_avg,
    distance_30d_avg,
    on_time_rate_30d_avg,
    rating_30d_avg,
    fuel_efficiency_30d_avg,
    deliveries_90d_avg,
    distance_90d_avg,
    on_time_rate_90d_avg,
    rating_90d_avg,
    fuel_efficiency_90d_avg,
    on_time_volatility_30d,
    fuel_efficiency_volatility_30d,
    performance_trend_7d_vs_30d,
    fuel_efficiency_trend_7d_vs_30d,
    NULL AS route_name,
    NULL AS route_type,
    NULL AS haul_type,
    NULL AS daily_trips,
    NULL AS avg_actual_duration,
    NULL AS avg_planned_duration,
    NULL AS avg_duration_ratio,
    NULL AS avg_customer_satisfaction,
    NULL AS total_fuel_cost,
    NULL AS total_revenue,
    NULL AS avg_fuel_cost_per_km,
    NULL AS severe_delays,
    NULL AS poor_ratings,
    NULL AS route_on_time_rate_7d_avg,
    NULL AS duration_ratio_7d_avg,
    NULL AS satisfaction_7d_avg,
    NULL AS route_fuel_efficiency_7d_avg,
    NULL AS route_on_time_rate_30d_avg,
    NULL AS duration_ratio_30d_avg,
    NULL AS satisfaction_30d_avg,
    NULL AS route_on_time_rate_90d_avg,
    NULL AS duration_ratio_90d_avg,
    NULL AS satisfaction_90d_avg,
    NULL AS route_on_time_volatility_30d,
    NULL AS duration_volatility_30d,
    NULL AS route_performance_rating,
    NULL AS route_risk_level,
    NULL AS make,
    NULL AS model,
    NULL AS model_year,
    NULL AS current_mileage,
    NULL AS maintenance_interval_miles,
    NULL AS last_maintenance_date,
    NULL AS next_maintenance_date,
    NULL AS avg_engine_temp,
    NULL AS avg_fuel_level,
    NULL AS avg_engine_rpm,
    NULL AS total_harsh_braking,
    NULL AS total_harsh_acceleration,
    NULL AS total_speeding_events,
    NULL AS avg_idle_time,
    NULL AS avg_engine_health,
    NULL AS max_engine_temp,
    NULL AS avg_fuel_consumption,
    NULL AS daily_maintenance_alerts,
    NULL AS unique_diagnostic_codes,
    NULL AS maintenance_events_7d,
    NULL AS maintenance_cost_7d,
    NULL AS maintenance_events_30d,
    NULL AS maintenance_cost_30d,
    NULL AS maintenance_events_90d,
    NULL AS maintenance_cost_90d,
    NULL AS maintenance_urgency,
    NULL AS days_since_last_maintenance,
    NULL AS miles_since_last_maintenance,
    NULL AS last_service_interval_days,
    NULL AS avg_engine_temp_7d,
    NULL AS avg_engine_health_7d,
    NULL AS harsh_braking_7d,
    NULL AS harsh_acceleration_7d,
    NULL AS maintenance_alerts_7d,
    NULL AS engine_health_14d_avg,
    NULL AS max_engine_temp_14d_avg,
    NULL AS avg_engine_temp_30d,
    NULL AS avg_engine_health_30d,
    NULL AS harsh_braking_30d,
    NULL AS harsh_acceleration_30d,
    NULL AS maintenance_alerts_30d,
    NULL AS avg_engine_health_90d,
    NULL AS harsh_braking_90d,
    NULL AS maintenance_alerts_90d,
    NULL AS engine_health_trend,
    NULL AS service_recommendation,
    NULL AS predictive_maintenance_score,
    NULL AS maintenance_risk_score,
    NULL AS next_maintenance_due_days

FROM LOGISTICS_DW_PROD.MARTS.ML_ROLLING_ANALYTICS
WHERE entity_type = 'vehicle'
    AND feature_date >= DATEADD('day', -90, CURRENT_DATE())

UNION ALL

-- Route rolling analytics
SELECT 
    'route' AS entity_type,
    entity_id,
    feature_date,
    NULL AS customer_name,
    NULL AS volume_segment,
    NULL AS customer_type,
    NULL AS daily_shipments,
    NULL AS daily_weight,
    NULL AS daily_volume,
    NULL AS daily_revenue,
    NULL AS daily_avg_rating,
    NULL AS daily_on_time_rate,
    NULL AS shipments_30d_avg,
    NULL AS revenue_30d_avg,
    NULL AS weight_30d_avg,
    NULL AS shipments_30d_total,
    NULL AS revenue_30d_total,
    NULL AS shipments_same_day_last_year,
    NULL AS revenue_same_day_last_year,
    NULL AS revenue_yoy_growth_percent,
    NULL AS shipments_7d_avg,
    NULL AS shipments_90d_avg,
    NULL AS activity_ratio_7d_vs_90d,
    NULL AS volume_trend_7d_vs_30d,
    NULL AS revenue_trend_30d_vs_90d,
    NULL AS days_since_first_order,
    NULL AS days_to_last_order,
    NULL AS shipment_volatility_30d,
    NULL AS behavior_consistency,
    NULL AS vehicle_type,
    origin_city,
    NULL AS daily_deliveries,
    NULL AS daily_distance_km,
    NULL AS daily_fuel_cost,
    NULL AS daily_delivery_cost,
    NULL AS daily_avg_speed_kmh,
    NULL AS daily_fuel_cost_per_km,
    NULL AS daily_profit,
    NULL AS deliveries_7d_avg,
    NULL AS distance_7d_avg,
    NULL AS on_time_rate_7d_avg,
    NULL AS rating_7d_avg,
    NULL AS fuel_efficiency_7d_avg,
    NULL AS deliveries_30d_avg,
    NULL AS distance_30d_avg,
    NULL AS on_time_rate_30d_avg,
    NULL AS rating_30d_avg,
    NULL AS fuel_efficiency_30d_avg,
    NULL AS deliveries_90d_avg,
    NULL AS distance_90d_avg,
    NULL AS on_time_rate_90d_avg,
    NULL AS rating_90d_avg,
    NULL AS fuel_efficiency_90d_avg,
    NULL AS on_time_volatility_30d,
    NULL AS fuel_efficiency_volatility_30d,
    NULL AS performance_trend_7d_vs_30d,
    NULL AS fuel_efficiency_trend_7d_vs_30d,
    route_name,
    route_type,
    haul_type,
    daily_trips,
    avg_actual_duration,
    avg_planned_duration,
    avg_duration_ratio,
    daily_on_time_rate AS avg_customer_satisfaction,
    total_fuel_cost,
    total_revenue,
    avg_fuel_cost_per_km,
    severe_delays,
    poor_ratings,
    on_time_rate_7d_avg AS route_on_time_rate_7d_avg,
    duration_ratio_7d_avg,
    satisfaction_7d_avg,
    fuel_efficiency_7d_avg AS route_fuel_efficiency_7d_avg,
    on_time_rate_30d_avg AS route_on_time_rate_30d_avg,
    duration_ratio_30d_avg,
    satisfaction_30d_avg,
    on_time_rate_90d_avg AS route_on_time_rate_90d_avg,
    duration_ratio_90d_avg,
    satisfaction_90d_avg,
    on_time_volatility_30d AS route_on_time_volatility_30d,
    duration_volatility_30d,
    route_performance_rating,
    route_risk_level,
    NULL AS make,
    NULL AS model,
    NULL AS model_year,
    NULL AS current_mileage,
    NULL AS maintenance_interval_miles,
    NULL AS last_maintenance_date,
    NULL AS next_maintenance_date,
    NULL AS avg_engine_temp,
    NULL AS avg_fuel_level,
    NULL AS avg_engine_rpm,
    NULL AS total_harsh_braking,
    NULL AS total_harsh_acceleration,
    NULL AS total_speeding_events,
    NULL AS avg_idle_time,
    NULL AS avg_engine_health,
    NULL AS max_engine_temp,
    NULL AS avg_fuel_consumption,
    NULL AS daily_maintenance_alerts,
    NULL AS unique_diagnostic_codes,
    NULL AS maintenance_events_7d,
    NULL AS maintenance_cost_7d,
    NULL AS maintenance_events_30d,
    NULL AS maintenance_cost_30d,
    NULL AS maintenance_events_90d,
    NULL AS maintenance_cost_90d,
    NULL AS maintenance_urgency,
    NULL AS days_since_last_maintenance,
    NULL AS miles_since_last_maintenance,
    NULL AS last_service_interval_days,
    NULL AS avg_engine_temp_7d,
    NULL AS avg_engine_health_7d,
    NULL AS harsh_braking_7d,
    NULL AS harsh_acceleration_7d,
    NULL AS maintenance_alerts_7d,
    NULL AS engine_health_14d_avg,
    NULL AS max_engine_temp_14d_avg,
    NULL AS avg_engine_temp_30d,
    NULL AS avg_engine_health_30d,
    NULL AS harsh_braking_30d,
    NULL AS harsh_acceleration_30d,
    NULL AS maintenance_alerts_30d,
    NULL AS avg_engine_health_90d,
    NULL AS harsh_braking_90d,
    NULL AS maintenance_alerts_90d,
    NULL AS engine_health_trend,
    NULL AS service_recommendation,
    NULL AS predictive_maintenance_score,
    NULL AS maintenance_risk_score,
    NULL AS next_maintenance_due_days

FROM LOGISTICS_DW_PROD.MARTS.ML_ROLLING_ANALYTICS
WHERE entity_type = 'route'
    AND feature_date >= DATEADD('day', -90, CURRENT_DATE())

UNION ALL

-- Maintenance rolling analytics
SELECT 
    'maintenance' AS entity_type,
    vehicle_id AS entity_id,
    feature_date,
    NULL AS customer_name,
    NULL AS volume_segment,
    NULL AS customer_type,
    NULL AS daily_shipments,
    NULL AS daily_weight,
    NULL AS daily_volume,
    NULL AS daily_revenue,
    NULL AS daily_avg_rating,
    NULL AS daily_on_time_rate,
    NULL AS shipments_30d_avg,
    NULL AS revenue_30d_avg,
    NULL AS weight_30d_avg,
    NULL AS shipments_30d_total,
    NULL AS revenue_30d_total,
    NULL AS shipments_same_day_last_year,
    NULL AS revenue_same_day_last_year,
    NULL AS revenue_yoy_growth_percent,
    NULL AS shipments_7d_avg,
    NULL AS shipments_90d_avg,
    NULL AS activity_ratio_7d_vs_90d,
    NULL AS volume_trend_7d_vs_30d,
    NULL AS revenue_trend_30d_vs_90d,
    NULL AS days_since_first_order,
    NULL AS days_to_last_order,
    NULL AS shipment_volatility_30d,
    NULL AS behavior_consistency,
    vehicle_type,
    NULL AS origin_city,
    NULL AS daily_deliveries,
    NULL AS daily_distance_km,
    NULL AS daily_fuel_cost,
    NULL AS daily_delivery_cost,
    NULL AS daily_avg_speed_kmh,
    NULL AS daily_fuel_cost_per_km,
    NULL AS daily_profit,
    NULL AS deliveries_7d_avg,
    NULL AS distance_7d_avg,
    NULL AS on_time_rate_7d_avg,
    NULL AS rating_7d_avg,
    NULL AS fuel_efficiency_7d_avg,
    NULL AS deliveries_30d_avg,
    NULL AS distance_30d_avg,
    NULL AS on_time_rate_30d_avg,
    NULL AS rating_30d_avg,
    NULL AS fuel_efficiency_30d_avg,
    NULL AS deliveries_90d_avg,
    NULL AS distance_90d_avg,
    NULL AS on_time_rate_90d_avg,
    NULL AS rating_90d_avg,
    NULL AS fuel_efficiency_90d_avg,
    NULL AS on_time_volatility_30d,
    NULL AS fuel_efficiency_volatility_30d,
    NULL AS performance_trend_7d_vs_30d,
    NULL AS fuel_efficiency_trend_7d_vs_30d,
    NULL AS route_name,
    NULL AS route_type,
    NULL AS haul_type,
    NULL AS daily_trips,
    NULL AS avg_actual_duration,
    NULL AS avg_planned_duration,
    NULL AS avg_duration_ratio,
    NULL AS avg_customer_satisfaction,
    NULL AS total_fuel_cost,
    NULL AS total_revenue,
    NULL AS avg_fuel_cost_per_km,
    NULL AS severe_delays,
    NULL AS poor_ratings,
    NULL AS route_on_time_rate_7d_avg,
    NULL AS duration_ratio_7d_avg,
    NULL AS satisfaction_7d_avg,
    NULL AS route_fuel_efficiency_7d_avg,
    NULL AS route_on_time_rate_30d_avg,
    NULL AS duration_ratio_30d_avg,
    NULL AS satisfaction_30d_avg,
    NULL AS route_on_time_rate_90d_avg,
    NULL AS duration_ratio_90d_avg,
    NULL AS satisfaction_90d_avg,
    NULL AS route_on_time_volatility_30d,
    NULL AS duration_volatility_30d,
    NULL AS route_performance_rating,
    NULL AS route_risk_level,
    make,
    model,
    model_year,
    current_mileage,
    maintenance_interval_miles,
    last_maintenance_date,
    next_maintenance_date,
    avg_engine_temp,
    avg_fuel_level,
    avg_engine_rpm,
    total_harsh_braking,
    total_harsh_acceleration,
    total_speeding_events,
    avg_idle_time,
    avg_engine_health,
    max_engine_temp,
    avg_fuel_consumption,
    daily_maintenance_alerts,
    unique_diagnostic_codes,
    maintenance_events_7d,
    maintenance_cost_7d,
    maintenance_events_30d,
    maintenance_cost_30d,
    maintenance_events_90d,
    maintenance_cost_90d,
    maintenance_urgency,
    days_since_last_maintenance,
    miles_since_last_maintenance,
    last_service_interval_days,
    avg_engine_temp_7d,
    avg_engine_health_7d,
    harsh_braking_7d,
    harsh_acceleration_7d,
    maintenance_alerts_7d,
    engine_health_14d_avg,
    max_engine_temp_14d_avg,
    avg_engine_temp_30d,
    avg_engine_health_30d,
    harsh_braking_30d,
    harsh_acceleration_30d,
    maintenance_alerts_30d,
    avg_engine_health_90d,
    harsh_braking_90d,
    maintenance_alerts_90d,
    engine_health_trend,
    service_recommendation,
    predictive_maintenance_score,
    maintenance_risk_score,
    next_maintenance_due_days

FROM LOGISTICS_DW_PROD.MARTS.ML_MAINTENANCE_FEATURES
WHERE feature_date >= DATEADD('day', -90, CURRENT_DATE())

ORDER BY entity_type, entity_id, feature_date DESC
