version: 2

models:
  - name: dim_date
    description: |
      Calendar dimension providing date-related attributes for time-based analysis:
      - Standard date attributes (year, month, day, quarter)
      - Business calendar attributes (weekday, weekend, holidays)
      - Fiscal year and period information
      - Date hierarchies for reporting
    columns:
      - name: date_key
        description: "Unique date key in YYYYMMDD format"
        tests: 
          - not_null
          - unique
      - name: date
        description: "Standard date value"
        tests: 
          - not_null
      - name: year
        description: "Year (YYYY)"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 2020
              max_value: 2030
      - name: month
        description: "Month (1-12)"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 12
      - name: day
        description: "Day of month (1-31)"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 31
      - name: quarter
        description: "Quarter (1-4)"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 4
      - name: day_of_week
        description: "Day of week (1=Sunday, 7=Saturday)"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 7
      - name: is_weekend
        description: "Flag indicating if date is weekend"
        tests:
          - not_null
          - accepted_values:
              values: [true, false]
      - name: is_holiday
        description: "Flag indicating if date is a holiday"
        tests:
          - not_null
          - accepted_values:
              values: [true, false]

  - name: dim_customer
    description: |
      Customer dimension containing all customer master data including:
      - Basic customer information (name, contact details)
      - Customer segmentation and tier classification  
      - Geographic information
      - Account status and preferences
      - Historical performance metrics
    columns:
      - name: customer_id
        description: "Unique identifier for each customer (surrogate key)"
        tests:
          - unique
          - not_null
      - name: customer_natural_key
        description: "Natural business key from source system"
        tests:
          - unique
          - not_null
      - name: customer_name
        description: "Full customer company name"
        tests:
          - not_null
      - name: customer_tier
        description: "Customer service tier (PREMIUM, STANDARD, BASIC)"
        tests:
          - not_null
          - accepted_values:
              values: ['PREMIUM', 'STANDARD', 'BASIC']
              quote: false
      - name: industry_vertical
        description: "Industry classification for the customer"
        tests:
          - accepted_values:
              values: ['RETAIL', 'MANUFACTURING', 'HEALTHCARE', 'TECHNOLOGY', 'AUTOMOTIVE', 'FOOD_BEVERAGE', 'OTHER']
      - name: credit_limit_usd
        description: "Customer credit limit in USD"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 10000000
      - name: customer_since_date
        description: "Date when customer relationship began"
        tests:
          - not_null
      - name: is_active
        description: "Flag indicating if customer is currently active"
        tests:
          - not_null
          - accepted_values:
              values: [true, false]
      - name: payment_terms_days
        description: "Standard payment terms in days"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 120
      - name: preferred_delivery_window
        description: "Customer's preferred delivery time window"
      - name: special_handling_requirements
        description: "Any special handling instructions or requirements"

  - name: dim_vehicle
    description: |
      Vehicle dimension containing comprehensive vehicle information:
      - Vehicle specifications (make, model, year, capacity)
      - Operational characteristics (fuel efficiency, maintenance schedule)
      - Current status and assignment
      - Historical performance metrics
    columns:
      - name: vehicle_id
        description: "Unique identifier for each vehicle (surrogate key)"
        tests:
          - unique
          - not_null
      - name: vehicle_number
        description: "Business vehicle number/license plate"
        tests:
          - unique
          - not_null
      - name: vehicle_type
        description: "Classification of vehicle type"
        tests:
          - not_null
          - accepted_values:
              values: ['TRUCK', 'VAN', 'MOTORCYCLE', 'TRAILER']
      - name: make_model
        description: "Vehicle make and model"
        tests:
          - not_null
      - name: model_year
        description: "Manufacturing year of the vehicle"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1990
              max_value: 2030
      - name: capacity_lbs
        description: "Maximum weight capacity in pounds"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 100
              max_value: 80000
      - name: fuel_efficiency_mpg
        description: "Average fuel efficiency in miles per gallon"
        tests:
          - dbt_utils.accepted_range:
              min_value: 3
              max_value: 50
      - name: maintenance_interval_miles
        description: "Recommended maintenance interval in miles"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 3000
              max_value: 25000
      - name: current_mileage
        description: "Current odometer reading"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1000000
      - name: vehicle_status
        description: "Current operational status"
        tests:
          - not_null
          - accepted_values:
              values: ['ACTIVE', 'MAINTENANCE', 'RETIRED', 'OUT_OF_SERVICE']

  - name: dim_location
    description: |
      Location dimension derived from routes (origin/destination IDs):
      - Geographic coordinates and address information
      - Location type classification (warehouse, customer, depot)
      - Service area and delivery zone information
      - Distance calculations and routing data
    columns:
      - name: location_id
        description: "Unique identifier for each location"
        tests:
          - not_null
          - unique
      - name: location_name
        description: "Human-readable location name"
        tests:
          - not_null
      - name: location_type
        description: "Type of location (WAREHOUSE, CUSTOMER, DEPOT, HUB)"
        tests:
          - not_null
          - accepted_values:
              values: ['WAREHOUSE', 'CUSTOMER', 'DEPOT', 'HUB']
      - name: address_line1
        description: "Primary address line"
        tests:
          - not_null
      - name: city
        description: "City name"
        tests:
          - not_null
      - name: state_province
        description: "State or province"
        tests:
          - not_null
      - name: postal_code
        description: "Postal/ZIP code"
        tests:
          - not_null
      - name: country
        description: "Country code"
        tests:
          - not_null
      - name: latitude
        description: "Geographic latitude coordinate"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: -90
              max_value: 90
      - name: longitude
        description: "Geographic longitude coordinate"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: -180
              max_value: 180
      - name: service_area
        description: "Service area classification"
      - name: delivery_zone
        description: "Delivery zone identifier"

  - name: dim_route
    description: |
      Route dimension derived from shipments:
      - Origin and destination location pairs
      - Route characteristics (distance, estimated time)
      - Route type and classification
      - Historical performance metrics
    columns:
      - name: route_id
        description: "Unique identifier for each route"
        tests:
          - not_null
          - unique
      - name: origin_location_id
        description: "Origin location identifier"
        tests:
          - not_null
          - relationships:
              to: ref('dim_location')
              field: location_id
      - name: destination_location_id
        description: "Destination location identifier"
        tests:
          - not_null
          - relationships:
              to: ref('dim_location')
              field: location_id
      - name: distance_miles
        description: "Standard distance between origin and destination"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 5000
      - name: estimated_travel_time_hours
        description: "Estimated travel time in hours"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0.1
              max_value: 48
      - name: route_type
        description: "Route classification (HIGHWAY, URBAN, RURAL, MIXED)"
        tests:
          - not_null
          - accepted_values:
              values: ['HIGHWAY', 'URBAN', 'RURAL', 'MIXED']
      - name: is_active
        description: "Flag indicating if route is currently active"
        tests:
          - not_null
          - accepted_values:
              values: [true, false]