version: 2

models:
  - name: tbl_dim_date
    description: |
      Calendar dimension providing date-related attributes for time-based analysis:
      - Standard date attributes (year, month, day, quarter)
      - Business calendar attributes (weekday, weekend, holidays)
      - Fiscal year and period information
      - Date hierarchies for reporting
    columns:
      - name: date_key
        description: "Unique date key in YYYYMMDD format"
        tests: 
          - not_null
          - unique
      - name: date
        description: "Standard date value"
        tests: 
          - not_null
      - name: year
        description: "Year (YYYY)"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 2020
              max_value: 2030
      - name: month
        description: "Month (1-12)"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 12
      - name: day_of_week
        description: "Day of week (1=Sunday, 7=Saturday)"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 7
      - name: is_weekend
        description: "Flag indicating if date is weekend"
        tests:
          - not_null
          - accepted_values:
              values: [true, false]

  - name: tbl_dim_customer
    description: |
      Customer dimension containing all customer master data including:
      - Basic customer information (name, contact details)
      - Customer segmentation and tier classification  
      - Geographic information
      - Account status and preferences
      - Historical performance metrics
    columns:
      - name: customer_id
        description: "Unique identifier for each customer"
        tests:
          - unique
          - not_null
      - name: customer_name
        description: "Full customer company name"
        tests:
          - not_null
      - name: customer_type
        description: "Customer type classification"
        tests:
          - not_null
      - name: customer_tier
        description: "Customer service tier"
        tests:
          - not_null
      - name: country
        description: "Customer country"
        tests:
          - not_null
      - name: industry_code
        description: "Industry classification code"
        tests:
          - not_null
      - name: credit_limit_usd
        description: "Customer credit limit in USD"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 10000000
      - name: is_active
        description: "Flag indicating if customer is currently active"
        tests:
          - not_null
          - accepted_values:
              values: [true, false]

  - name: tbl_dim_location
    description: |
      Location dimension containing geographic and address information:
      - Physical addresses and coordinates
      - Geographic hierarchies (country, state, city)
      - Location types and classifications
      - Service area definitions
    columns:
      - name: location_id
        description: "Unique identifier for each location"
        tests:
          - unique
          - not_null

  - name: tbl_dim_route
    description: |
      Route dimension containing route master data:
      - Origin and destination locations
      - Distance and travel time estimates
      - Route classifications and types
      - Historical performance metrics
    columns:
      - name: route_id
        description: "Unique identifier for each route"
        tests:
          - unique
          - not_null
      - name: origin_location_id
        description: "Origin location identifier"
        tests:
          - not_null
      - name: destination_location_id
        description: "Destination location identifier"
        tests:
          - not_null
      - name: distance_km
        description: "Route distance in kilometers"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 10000

  - name: tbl_dim_vehicle
    description: |
      Vehicle dimension containing fleet master data:
      - Vehicle specifications and capabilities
      - Maintenance history and schedules
      - Performance metrics and utilization
      - Cost and depreciation information
    columns:
      - name: vehicle_id
        description: "Unique identifier for each vehicle"
        tests:
          - unique
          - not_null
      - name: vehicle_type
        description: "Type of vehicle"
        tests:
          - not_null
          - accepted_values:
              values: ['TRUCK', 'VAN', 'MOTORCYCLE', 'TRAILER']
      - name: capacity_kg
        description: "Vehicle capacity in kilograms"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 50000
      - name: fuel_efficiency_mpg
        description: "Fuel efficiency in miles per gallon"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      - name: make
        description: "Vehicle manufacturer"
        tests:
          - not_null
      - name: model
        description: "Vehicle model"
        tests:
          - not_null
      - name: model_year
        description: "Year the vehicle was manufactured"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1990
              max_value: 2030
      - name: vehicle_status
        description: "Current status of the vehicle"
        tests:
          - not_null
          - accepted_values:
              values: ['ACTIVE', 'INACTIVE', 'MAINTENANCE', 'RETIRED']

  - name: tbl_dim_weather
    description: |
      Weather dimension containing weather condition data:
      - Temperature, precipitation, and visibility metrics
      - Weather impact scores for logistics operations
      - Historical weather patterns and trends
    columns:
      - name: weather_id
        description: "Unique identifier for each weather record"
        tests:
          - unique
          - not_null
      - name: location_id
        description: "Location identifier"
        tests:
          - not_null
      - name: weather_date
        description: "Date of weather reading"
        tests:
          - not_null
      - name: temperature_c
        description: "Temperature in Celsius"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: -50
              max_value: 60
      - name: precipitation_mm
        description: "Precipitation in millimeters"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 500
      - name: weather_condition
        description: "Weather condition description"
        tests:
          - not_null
          - accepted_values:
              values: ['CLEAR', 'CLOUDY', 'RAIN', 'SNOW', 'FOG', 'STORM']

  - name: tbl_dim_traffic_conditions
    description: |
      Traffic conditions dimension containing traffic data:
      - Traffic volume and congestion levels
      - Speed and delay metrics
      - Peak hour and severity classifications
    columns:
      - name: traffic_id
        description: "Unique identifier for each traffic record"
        tests:
          - unique
          - not_null
      - name: route_id
        description: "Route identifier"
        tests:
          - not_null
      - name: traffic_date
        description: "Date of traffic reading"
        tests:
          - not_null
      - name: congestion_level
        description: "Traffic congestion level"
        tests:
          - not_null
          - accepted_values:
              values: ['LOW', 'MODERATE', 'HIGH', 'SEVERE']
      - name: average_speed_kmh
        description: "Average speed in kilometers per hour"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 200

  - name: tbl_dim_vehicle_maintenance
    description: |
      Vehicle maintenance dimension containing maintenance data:
      - Maintenance types and schedules
      - Cost and performance metrics
      - Risk assessment and predictions
    columns:
      - name: maintenance_id
        description: "Unique identifier for each maintenance record"
        tests:
          - unique
          - not_null
      - name: vehicle_id
        description: "Vehicle identifier"
        tests:
          - not_null
      - name: maintenance_type
        description: "Type of maintenance performed"
        tests:
          - not_null
          - accepted_values:
              values: ['ROUTINE', 'PREVENTIVE', 'CORRECTIVE', 'EMERGENCY', 'INSPECTION']
      - name: maintenance_date
        description: "Date when maintenance was performed"
        tests:
          - not_null
      - name: maintenance_cost_usd
        description: "Cost of maintenance in USD"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 10000
      - name: maintenance_status
        description: "Status of maintenance"
        tests:
          - not_null
          - accepted_values:
              values: ['COMPLETED', 'SCHEDULED', 'IN_PROGRESS', 'CANCELLED']