-- =====================================================
-- Warehouse Configuration for Logistics Analytics Platform
-- =====================================================

-- Create optimized warehouses for different workloads
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH_XS
WITH WAREHOUSE_SIZE = 'X-SMALL'
     AUTO_SUSPEND = 60
     AUTO_RESUME = TRUE
     INITIALLY_SUSPENDED = TRUE
     COMMENT = 'Small warehouse for development and light workloads';

CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH_SMALL
WITH WAREHOUSE_SIZE = 'SMALL'
     AUTO_SUSPEND = 60
     AUTO_RESUME = TRUE
     INITIALLY_SUSPENDED = TRUE
     COMMENT = 'Small warehouse for staging and testing';

CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH_MEDIUM
WITH WAREHOUSE_SIZE = 'MEDIUM'
     AUTO_SUSPEND = 60
     AUTO_RESUME = TRUE
     INITIALLY_SUSPENDED = TRUE
     COMMENT = 'Medium warehouse for production analytics and ML training';

CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH_LARGE
WITH WAREHOUSE_SIZE = 'LARGE'
     AUTO_SUSPEND = 60
     AUTO_RESUME = TRUE
     INITIALLY_SUSPENDED = TRUE
     COMMENT = 'Large warehouse for heavy ML model training and data science';

CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH_XLARGE
WITH WAREHOUSE_SIZE = 'X-LARGE'
     AUTO_SUSPEND = 60
     AUTO_RESUME = TRUE
     INITIALLY_SUSPENDED = TRUE
     COMMENT = 'Extra large warehouse for intensive ML workloads';

-- Legacy warehouse names (for backward compatibility)
CREATE WAREHOUSE IF NOT EXISTS WH_LOADING
WITH WAREHOUSE_SIZE = 'LARGE'
     AUTO_SUSPEND = 60
     AUTO_RESUME = TRUE
     INITIALLY_SUSPENDED = TRUE
     COMMENT = 'Legacy warehouse for data loading operations';

CREATE WAREHOUSE IF NOT EXISTS WH_ANALYTICS
WITH WAREHOUSE_SIZE = 'MEDIUM'
     AUTO_SUSPEND = 300
     AUTO_RESUME = TRUE
     INITIALLY_SUSPENDED = TRUE
     COMMENT = 'Legacy warehouse for analytics and reporting';

CREATE WAREHOUSE IF NOT EXISTS WH_ML
WITH WAREHOUSE_SIZE = 'XLARGE'
     AUTO_SUSPEND = 60
     AUTO_RESUME = TRUE
     INITIALLY_SUSPENDED = TRUE
     COMMENT = 'Legacy warehouse for ML model training and scoring';

-- Grant warehouse permissions to roles
GRANT USAGE ON WAREHOUSE COMPUTE_WH_XS TO ROLE DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE COMPUTE_WH_SMALL TO ROLE DATA_ANALYST;
GRANT USAGE ON WAREHOUSE COMPUTE_WH_MEDIUM TO ROLE ML_ENGINEER;
GRANT USAGE ON WAREHOUSE COMPUTE_WH_LARGE TO ROLE DATA_SCIENTIST;
GRANT USAGE ON WAREHOUSE COMPUTE_WH_XLARGE TO ROLE DATA_SCIENTIST;

-- Legacy warehouse permissions
GRANT USAGE ON WAREHOUSE WH_LOADING TO ROLE DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE WH_ANALYTICS TO ROLE DATA_ANALYST;
GRANT USAGE ON WAREHOUSE WH_ML TO ROLE ML_ENGINEER;
GRANT USAGE ON WAREHOUSE WH_ML TO ROLE DATA_SCIENTIST;

-- Set warehouse properties for cost optimization
ALTER WAREHOUSE COMPUTE_WH_XS SET 
    AUTO_SUSPEND = 60,
    AUTO_RESUME = TRUE,
    COMMENT = 'Optimized for development and automation tasks';

ALTER WAREHOUSE COMPUTE_WH_SMALL SET 
    AUTO_SUSPEND = 60,
    AUTO_RESUME = TRUE,
    COMMENT = 'Optimized for staging and testing workloads';

ALTER WAREHOUSE COMPUTE_WH_MEDIUM SET 
    AUTO_SUSPEND = 60,
    AUTO_RESUME = TRUE,
    COMMENT = 'Optimized for production analytics and ML training';

ALTER WAREHOUSE COMPUTE_WH_LARGE SET 
    AUTO_SUSPEND = 60,
    AUTO_RESUME = TRUE,
    COMMENT = 'Optimized for heavy ML model training';

ALTER WAREHOUSE COMPUTE_WH_XLARGE SET 
    AUTO_SUSPEND = 60,
    AUTO_RESUME = TRUE,
    COMMENT = 'Optimized for intensive ML workloads';

-- Create resource monitors for cost control
CREATE RESOURCE MONITOR IF NOT EXISTS RM_COMPUTE_WH_XS
WITH CREDIT_QUOTA = 100
     FREQUENCY = 'MONTHLY'
     START_TIMESTAMP = 'IMMEDIATELY'
     TRIGGERS
     ON 80 PERCENT DO NOTIFY
     ON 100 PERCENT DO SUSPEND;

CREATE RESOURCE MONITOR IF NOT EXISTS RM_COMPUTE_WH_SMALL
WITH CREDIT_QUOTA = 500
     FREQUENCY = 'MONTHLY'
     START_TIMESTAMP = 'IMMEDIATELY'
     TRIGGERS
     ON 80 PERCENT DO NOTIFY
     ON 100 PERCENT DO SUSPEND;

CREATE RESOURCE MONITOR IF NOT EXISTS RM_COMPUTE_WH_MEDIUM
WITH CREDIT_QUOTA = 1000
     FREQUENCY = 'MONTHLY'
     START_TIMESTAMP = 'IMMEDIATELY'
     TRIGGERS
     ON 80 PERCENT DO NOTIFY
     ON 100 PERCENT DO SUSPEND;

CREATE RESOURCE MONITOR IF NOT EXISTS RM_COMPUTE_WH_LARGE
WITH CREDIT_QUOTA = 2000
     FREQUENCY = 'MONTHLY'
     START_TIMESTAMP = 'IMMEDIATELY'
     TRIGGERS
     ON 80 PERCENT DO NOTIFY
     ON 100 PERCENT DO SUSPEND;

CREATE RESOURCE MONITOR IF NOT EXISTS RM_COMPUTE_WH_XLARGE
WITH CREDIT_QUOTA = 5000
     FREQUENCY = 'MONTHLY'
     START_TIMESTAMP = 'IMMEDIATELY'
     TRIGGERS
     ON 80 PERCENT DO NOTIFY
     ON 100 PERCENT DO SUSPEND;

-- Assign resource monitors to warehouses
ALTER WAREHOUSE COMPUTE_WH_XS SET RESOURCE_MONITOR = RM_COMPUTE_WH_XS;
ALTER WAREHOUSE COMPUTE_WH_SMALL SET RESOURCE_MONITOR = RM_COMPUTE_WH_SMALL;
ALTER WAREHOUSE COMPUTE_WH_MEDIUM SET RESOURCE_MONITOR = RM_COMPUTE_WH_MEDIUM;
ALTER WAREHOUSE COMPUTE_WH_LARGE SET RESOURCE_MONITOR = RM_COMPUTE_WH_LARGE;
ALTER WAREHOUSE COMPUTE_WH_XLARGE SET RESOURCE_MONITOR = RM_COMPUTE_WH_XLARGE;