-- Create role hierarchy for data governance
CREATE ROLE IF NOT EXISTS DATA_ENGINEER;
CREATE ROLE IF NOT EXISTS DATA_ANALYST; 
CREATE ROLE IF NOT EXISTS DATA_SCIENTIST;
CREATE ROLE IF NOT EXISTS BUSINESS_USER;
CREATE ROLE IF NOT EXISTS DATA_STEWARD;

-- Grant basic permissions
GRANT ROLE DATA_ANALYST TO ROLE DATA_ENGINEER;
GRANT ROLE BUSINESS_USER TO ROLE DATA_ANALYST;
GRANT ROLE DATA_SCIENTIST TO ROLE DATA_ENGINEER;

-- Database and schema permissions
GRANT USAGE ON DATABASE LOGISTICS_DW_PROD TO ROLE DATA_ENGINEER;
GRANT USAGE ON DATABASE LOGISTICS_DW_PROD TO ROLE DATA_ANALYST;
GRANT USAGE ON DATABASE LOGISTICS_DW_PROD TO ROLE DATA_SCIENTIST;
GRANT USAGE ON DATABASE LOGISTICS_DW_PROD TO ROLE BUSINESS_USER;

-- Schema-level permissions
GRANT USAGE ON SCHEMA LOGISTICS_DW_PROD.RAW TO ROLE DATA_ENGINEER;
GRANT USAGE ON SCHEMA LOGISTICS_DW_PROD.STAGING TO ROLE DATA_ENGINEER;
GRANT USAGE ON SCHEMA LOGISTICS_DW_PROD.MARTS TO ROLE DATA_ANALYST;
GRANT USAGE ON SCHEMA LOGISTICS_DW_PROD.ANALYTICS TO ROLE BUSINESS_USER;

-- Table-level permissions with data masking
GRANT SELECT ON ALL TABLES IN SCHEMA LOGISTICS_DW_PROD.MARTS TO ROLE DATA_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA LOGISTICS_DW_PROD.ANALYTICS TO ROLE BUSINESS_USER;

-- Future grants
GRANT SELECT ON FUTURE TABLES IN SCHEMA LOGISTICS_DW_PROD.MARTS TO ROLE DATA_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA LOGISTICS_DW_PROD.ANALYTICS TO ROLE BUSINESS_USER;

-- Grant warehouse permissions
GRANT USAGE ON WAREHOUSE WH_ANALYTICS TO ROLE DATA_ANALYST;
GRANT USAGE ON WAREHOUSE WH_ML TO ROLE DATA_SCIENTIST;
