version: 2

models:
  - name: vw_consolidated_dashboard
    description: |
      Comprehensive business intelligence dashboard combining performance and executive analytics:
      - Operational metrics (on-time delivery, route efficiency, capacity utilization)
      - Financial performance (costs, revenue, margins, profitability trends)
      - Customer satisfaction indicators and service level metrics
      - Rolling analytics (7d, 30d, 90d) and trend analysis
      - Week-over-week and year-over-year comparisons
      - Performance ratings and alert indicators
    meta:
      owner: "analytics-team"
      refresh_frequency: "every 4 hours"
      business_users: ["operations", "finance", "executive"]
    columns:
      - name: shipment_date
        description: "Date for the metrics calculation"
        tests:
          - not_null
      - name: daily_deliveries
        description: "Total number of deliveries for the day"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: on_time_percentage
        description: "Percentage of shipments delivered on time"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      - name: satisfaction_score
        description: "Average customer satisfaction score"
        tests:
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 10
      - name: revenue
        description: "Total revenue for the day"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: profit
        description: "Total profit for the day"
        tests:
          - not_null
      - name: profit_margin_percentage
        description: "Overall profit margin percentage"
        tests:
          - dbt_utils.accepted_range:
              min_value: -50
              max_value: 50
      - name: overall_performance_score
        description: "Composite performance score (0-100)"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      - name: volume_trend
        description: "Volume trend classification (increasing/decreasing/stable)"
        tests:
          - accepted_values:
              values: ['increasing', 'decreasing', 'stable']
      - name: performance_trend
        description: "Performance trend classification (improving/declining/stable)"
        tests:
          - accepted_values:
              values: ['improving', 'declining', 'stable']
      - name: revenue_trend
        description: "Revenue trend classification (growing/declining/stable)"
        tests:
          - accepted_values:
              values: ['growing', 'declining', 'stable']
      - name: alert_status
        description: "Alert status for performance issues"
        tests:
          - accepted_values:
              values: ['performance_alert', 'satisfaction_alert', 'revenue_alert', 'normal']

  - name: vw_sustainability_metrics
    description: |
      Environmental impact and sustainability tracking:
      - Carbon emissions tracking
      - Fuel efficiency metrics
      - Route optimization savings
      - Green logistics initiatives performance
    meta:
      owner: "sustainability-team"
      compliance: ["ESG_REPORTING", "CARBON_ACCOUNTING"]
    columns:
      - name: shipment_date
        description: "Date for sustainability metrics"
        tests:
          - not_null
      - name: origin_city
        description: "Origin city for the metrics"
        tests:
          - not_null
      - name: origin_state
        description: "Origin state for the metrics"
        tests:
          - not_null
      - name: active_vehicles
        description: "Number of active vehicles"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: electric_vehicles
        description: "Number of electric vehicles"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: hybrid_vehicles
        description: "Number of hybrid vehicles"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: traditional_vehicles
        description: "Number of traditional vehicles"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: electric_vehicle_percentage
        description: "Percentage of electric vehicles"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      - name: eco_friendly_percentage
        description: "Percentage of eco-friendly vehicles"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      - name: total_distance_km
        description: "Total distance traveled in kilometers"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: fuel_consumption_liters
        description: "Total fuel consumption in liters"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: co2_emissions_kg
        description: "Total CO2 emissions in kilograms"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: co2_emissions_tonnes
        description: "Total CO2 emissions in tonnes"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: total_deliveries
        description: "Total number of deliveries"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: avg_fuel_efficiency_l_per_100km
        description: "Average fuel efficiency in liters per 100km"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 50
      - name: co2_grams_per_km
        description: "CO2 emissions in grams per kilometer"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1000
      - name: co2_kg_per_delivery
        description: "CO2 emissions in kg per delivery"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      - name: avg_vehicle_age_years
        description: "Average vehicle age in years"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 30
      - name: modern_vehicles
        description: "Number of modern vehicles"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: older_vehicles
        description: "Number of older vehicles"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: modern_fleet_percentage
        description: "Percentage of modern fleet"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      - name: sustainability_score
        description: "Overall sustainability score"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      - name: electrification_maturity
        description: "Electrification maturity level"
        tests:
          - accepted_values:
              values: ['LOW', 'MEDIUM', 'HIGH', 'ADVANCED']
      - name: co2_emissions_same_date_last_year
        description: "CO2 emissions same date last year"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
      - name: co2_yoy_change_percent
        description: "Year-over-year CO2 change percentage"
        tests:
          - dbt_utils.accepted_range:
              min_value: -100
              max_value: 1000
      - name: carbon_target_status
        description: "Carbon target status"
        tests:
          - accepted_values:
              values: ['ON_TRACK', 'BEHIND', 'EXCEEDED', 'NOT_SET']

  - name: vw_data_lineage
    description: |
      Data lineage tracking for the logistics analytics platform:
      - Model dependencies and relationships
      - Column-level lineage tracking
      - Data flow from raw to marts
      - Ingestion method and source system tracking
    meta:
      owner: "data-engineering"
      refresh_frequency: "daily"
    columns:
      - name: layer
        description: "Data layer (RAW, STAGING, MARTS)"
        tests:
          - not_null
          - accepted_values:
              values: ['RAW', 'STAGING', 'MARTS']
      - name: table_name
        description: "Name of the table or model"
        tests:
          - not_null
      - name: source_system
        description: "Source system or transformation tool"
        tests:
          - not_null
      - name: ingestion_method
        description: "Method used for data ingestion or transformation"
        tests:
          - not_null
      - name: last_updated
        description: "Last update timestamp"
        tests:
          - not_null
      - name: materialization
        description: "dbt materialization type"
      - name: tags
        description: "dbt tags associated with the model"
      - name: column_count
        description: "Number of columns in the table"
        tests:
          - dbt_utils.accepted_range:
              min_value: 1
      - name: columns
        description: "Comma-separated list of column names"

  - name: vw_data_quality_sla
    description: |
      Data Quality SLA monitoring and compliance tracking:
      - Data freshness SLA compliance
      - Completeness SLA compliance
      - Accuracy SLA compliance
      - Consistency SLA compliance
    meta:
      owner: "data-engineering"
      refresh_frequency: "hourly"
    columns:
      - name: sla_type
        description: "Type of SLA being measured"
        tests:
          - not_null
          - accepted_values:
              values: ['data_freshness', 'completeness', 'accuracy', 'consistency']
      - name: table_name
        description: "Table or system being monitored"
        tests:
          - not_null
      - name: sla_status
        description: "SLA status (EXCELLENT, GOOD, ACCEPTABLE, POOR)"
        tests:
          - not_null
          - accepted_values:
              values: ['EXCELLENT', 'GOOD', 'ACCEPTABLE', 'POOR']
      - name: sla_result
        description: "SLA result (PASS, FAIL)"
        tests:
          - not_null
          - accepted_values:
              values: ['PASS', 'FAIL']
      - name: sla_threshold_hours
        description: "SLA threshold in hours or percentage"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0

  - name: vw_data_freshness_monitoring
    description: |
      Data freshness monitoring for all data sources and models:
      - Last update timestamps
      - Data age calculations
      - Freshness alerts and warnings
    meta:
      owner: "data-engineering"
      refresh_frequency: "hourly"
    columns:
      - name: table_name
        description: "Name of the table or model"
        tests:
          - not_null
      - name: data_source
        description: "Data source system"
        tests:
          - not_null
      - name: latest_update
        description: "Latest update timestamp"
        tests:
          - not_null
      - name: total_records
        description: "Total number of records"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: recent_updates
        description: "Number of recent updates"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: minutes_since_update
        description: "Minutes since last update"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: sla_minutes
        description: "SLA threshold in minutes"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: freshness_status
        description: "Freshness status"
        tests:
          - not_null
          - accepted_values:
              values: ['FRESH', 'STALE', 'CRITICAL', 'WARNING']
      - name: sla_compliant
        description: "SLA compliance flag"
        tests:
          - not_null
          - accepted_values:
              values: [true, false]
      - name: freshness_health_score
        description: "Freshness health score"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      - name: alert_priority
        description: "Alert priority level"
        tests:
          - not_null
          - accepted_values:
              values: ['HIGH', 'MEDIUM', 'LOW', 'NONE']
      - name: check_timestamp
        description: "Timestamp when check was performed"
        tests:
          - not_null

  - name: vw_ai_recommendations
    description: |
      AI-powered recommendations for logistics optimization:
      - Route optimization suggestions
      - Vehicle maintenance recommendations
      - Cost reduction opportunities
      - Performance improvement suggestions
    meta:
      owner: "ai-team"
      refresh_frequency: "daily"
    columns:
      - name: recommendation_type
        description: "Type of recommendation"
        tests:
          - not_null
          - accepted_values:
              values: ['route_optimization', 'maintenance', 'cost_reduction', 'performance', 'vehicle_assignment', 'customer_retention']
      - name: entity_id
        description: "Entity identifier"
        tests:
          - not_null
      - name: entity_name
        description: "Entity name"
        tests:
          - not_null
      - name: priority_level
        description: "Recommendation priority level"
        tests:
          - not_null
          - accepted_values:
              values: ['high', 'medium', 'low']
      - name: issue_description
        description: "Description of the issue"
        tests:
          - not_null
      - name: recommendation
        description: "Recommendation details"
        tests:
          - not_null
      - name: impact_hours_saved
        description: "Impact in hours saved"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
      - name: estimated_cost_impact
        description: "Estimated cost impact"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
      - name: confidence_score
        description: "AI confidence score"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      - name: generated_at
        description: "Timestamp when recommendation was generated"
        tests:
          - not_null