version: 2

models:
  - name: consolidated_dashboard
    description: |
      Comprehensive business intelligence dashboard combining performance and executive analytics:
      - Operational metrics (on-time delivery, route efficiency, capacity utilization)
      - Financial performance (costs, revenue, margins, profitability trends)
      - Customer satisfaction indicators and service level metrics
      - Rolling analytics (7d, 30d, 90d) and trend analysis
      - Week-over-week and year-over-year comparisons
      - Performance ratings and alert indicators
    meta:
      owner: "analytics-team"
      refresh_frequency: "every 4 hours"
      business_users: ["operations", "finance", "executive"]
    columns:
      - name: shipment_date
        description: "Date for the metrics calculation"
        tests:
          - not_null
      - name: daily_deliveries
        description: "Total number of deliveries for the day"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: on_time_percentage
        description: "Percentage of shipments delivered on time"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      - name: satisfaction_score
        description: "Average customer satisfaction score"
        tests:
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 10
      - name: revenue
        description: "Total revenue for the day"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: profit
        description: "Total profit for the day"
        tests:
          - not_null
      - name: profit_margin_percentage
        description: "Overall profit margin percentage"
        tests:
          - dbt_utils.accepted_range:
              min_value: -50
              max_value: 50
      - name: overall_performance_score
        description: "Composite performance score (0-100)"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      - name: volume_trend
        description: "Volume trend classification (increasing/decreasing/stable)"
        tests:
          - accepted_values:
              values: ['increasing', 'decreasing', 'stable']
      - name: performance_trend
        description: "Performance trend classification (improving/declining/stable)"
        tests:
          - accepted_values:
              values: ['improving', 'declining', 'stable']
      - name: revenue_trend
        description: "Revenue trend classification (growing/declining/stable)"
        tests:
          - accepted_values:
              values: ['growing', 'declining', 'stable']
      - name: alert_status
        description: "Alert status for performance issues"
        tests:
          - accepted_values:
              values: ['performance_alert', 'satisfaction_alert', 'revenue_alert', 'normal']

  - name: sustainability_metrics
    description: |
      Environmental impact and sustainability tracking:
      - Carbon emissions tracking
      - Fuel efficiency metrics
      - Route optimization savings
      - Green logistics initiatives performance
    meta:
      owner: "sustainability-team"
      compliance: ["ESG_REPORTING", "CARBON_ACCOUNTING"]
    columns:
      - name: metric_date
        description: "Date for sustainability metrics"
        tests:
          - not_null
      - name: total_carbon_emissions_kg
        description: "Total carbon emissions in kg CO2"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: carbon_per_mile_kg
        description: "Carbon emissions per mile traveled"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 2
      - name: fuel_efficiency_mpg
        description: "Fleet average fuel efficiency"
        tests:
          - dbt_utils.accepted_range:
              min_value: 3
              max_value: 20
      - name: route_optimization_savings_usd
        description: "Cost savings from route optimization"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
      - name: green_delivery_percentage
        description: "Percentage of deliveries using eco-friendly vehicles"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100