version: 2

models:
  - name: vw_consolidated_dashboard
    description: |
      Comprehensive business intelligence dashboard combining performance and executive analytics:
      - Operational metrics (on-time delivery, route efficiency, capacity utilization)
      - Financial performance (costs, revenue, margins, profitability trends)
      - Customer satisfaction indicators and service level metrics
      - Rolling analytics (7d, 30d, 90d) and trend analysis
      - Week-over-week and year-over-year comparisons
      - Performance ratings and alert indicators
    meta:
      owner: "analytics-team"
      refresh_frequency: "every 4 hours"
      business_users: ["operations", "finance", "executive"]
    columns:
      - name: shipment_date
        description: "Date for the metrics calculation"
        tests:
          - not_null
      - name: daily_deliveries
        description: "Total number of deliveries for the day"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: on_time_percentage
        description: "Percentage of shipments delivered on time"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      - name: satisfaction_score
        description: "Average customer satisfaction score"
        tests:
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 10
      - name: revenue
        description: "Total revenue for the day"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: profit
        description: "Total profit for the day"
        tests:
          - not_null
      - name: profit_margin_percentage
        description: "Overall profit margin percentage"
        tests:
          - dbt_utils.accepted_range:
              min_value: -50
              max_value: 50
      - name: overall_performance_score
        description: "Composite performance score (0-100)"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      - name: volume_trend
        description: "Volume trend classification (increasing/decreasing/stable)"
        tests:
          - accepted_values:
              values: ['increasing', 'decreasing', 'stable']
      - name: performance_trend
        description: "Performance trend classification (improving/declining/stable)"
        tests:
          - accepted_values:
              values: ['improving', 'declining', 'stable']
      - name: revenue_trend
        description: "Revenue trend classification (growing/declining/stable)"
        tests:
          - accepted_values:
              values: ['growing', 'declining', 'stable']
      - name: alert_status
        description: "Alert status for performance issues"
        tests:
          - accepted_values:
              values: ['performance_alert', 'satisfaction_alert', 'revenue_alert', 'normal']

  - name: vw_sustainability_metrics
    description: |
      Environmental impact and sustainability tracking:
      - Carbon emissions tracking
      - Fuel efficiency metrics
      - Route optimization savings
      - Green logistics initiatives performance
    meta:
      owner: "sustainability-team"
      compliance: ["ESG_REPORTING", "CARBON_ACCOUNTING"]
    columns:
      - name: metric_date
        description: "Date for sustainability metrics"
        tests:
          - not_null
      - name: total_carbon_emissions_kg
        description: "Total carbon emissions in kg CO2"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: carbon_per_mile_kg
        description: "Carbon emissions per mile traveled"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 2
      - name: fuel_efficiency_mpg
        description: "Fleet average fuel efficiency"
        tests:
          - dbt_utils.accepted_range:
              min_value: 3
              max_value: 20
      - name: route_optimization_savings_usd
        description: "Cost savings from route optimization"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
      - name: green_delivery_percentage
        description: "Percentage of deliveries using eco-friendly vehicles"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100

  - name: vw_data_lineage
    description: |
      Data lineage tracking for the logistics analytics platform:
      - Model dependencies and relationships
      - Column-level lineage tracking
      - Data flow from raw to marts
      - Ingestion method and source system tracking
    meta:
      owner: "data-engineering"
      refresh_frequency: "daily"
    columns:
      - name: layer
        description: "Data layer (RAW, STAGING, MARTS)"
        tests:
          - not_null
          - accepted_values:
              values: ['RAW', 'STAGING', 'MARTS']
      - name: table_name
        description: "Name of the table or model"
        tests:
          - not_null
      - name: source_system
        description: "Source system or transformation tool"
        tests:
          - not_null
      - name: ingestion_method
        description: "Method used for data ingestion or transformation"
        tests:
          - not_null
      - name: last_updated
        description: "Last update timestamp"
        tests:
          - not_null
      - name: materialization
        description: "dbt materialization type"
      - name: tags
        description: "dbt tags associated with the model"
      - name: column_count
        description: "Number of columns in the table"
        tests:
          - dbt_utils.accepted_range:
              min_value: 1
      - name: columns
        description: "Comma-separated list of column names"

  - name: vw_data_quality_sla
    description: |
      Data Quality SLA monitoring and compliance tracking:
      - Data freshness SLA compliance
      - Completeness SLA compliance
      - Accuracy SLA compliance
      - Consistency SLA compliance
    meta:
      owner: "data-engineering"
      refresh_frequency: "hourly"
    columns:
      - name: sla_type
        description: "Type of SLA being measured"
        tests:
          - not_null
          - accepted_values:
              values: ['data_freshness', 'completeness', 'accuracy', 'consistency']
      - name: table_name
        description: "Table or system being monitored"
        tests:
          - not_null
      - name: sla_status
        description: "SLA status (EXCELLENT, GOOD, ACCEPTABLE, POOR)"
        tests:
          - not_null
          - accepted_values:
              values: ['EXCELLENT', 'GOOD', 'ACCEPTABLE', 'POOR']
      - name: sla_result
        description: "SLA result (PASS, FAIL)"
        tests:
          - not_null
          - accepted_values:
              values: ['PASS', 'FAIL']
      - name: sla_threshold_hours
        description: "SLA threshold in hours or percentage"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0