version: 2

models:
  - name: tbl_fact_shipments
    description: |
      Core shipment fact table containing transactional shipment data:
      - Shipment identifiers and foreign keys to dimensions
      - Calculated metrics (distance, time, costs)
      - Performance indicators (on-time delivery, efficiency scores)
      - Financial data (revenue, costs, margins)
    meta:
      owner: "data-engineering"
      contains_pii: false
      update_frequency: "hourly"
    columns:
      - name: shipment_id
        description: "Unique identifier for each shipment"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Foreign key to customer dimension"
        tests:
          - not_null
          - relationships:
              to: ref('tbl_dim_customer')
              field: customer_id
      - name: vehicle_id
        description: "Foreign key to vehicle dimension"
        tests:
          - relationships:
              to: ref('tbl_dim_vehicle')  
              field: vehicle_id
      - name: route_id
        description: "Foreign key to route dimension"
        tests:
          - relationships:
              to: ref('tbl_dim_route')
              field: route_id
      - name: date_key
        description: "Foreign key to date dimension for shipment date"
        tests:
          - not_null
          - relationships:
              to: ref('tbl_dim_date')
              field: date_key
      - name: distance_km
        description: "Distance traveled for shipment in kilometers"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 8000
      - name: actual_duration_minutes
        description: "Actual time taken for delivery in minutes"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 43200
      - name: planned_duration_minutes
        description: "Originally planned delivery time in minutes"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 43200
      - name: fuel_cost
        description: "Total fuel cost for the shipment"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 10000
      - name: delivery_cost
        description: "Delivery cost for the shipment"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 5000
      - name: revenue
        description: "Revenue generated from the shipment"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100000
      - name: profit_margin_pct
        description: "Profit margin percentage"
        tests:
          - dbt_utils.accepted_range:
              min_value: -100
              max_value: 100
      - name: carbon_emissions_kg
        description: "Carbon emissions in kilograms"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1000
      - name: weather_delay_minutes
        description: "Weather-related delay in minutes"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1440
      - name: traffic_delay_minutes
        description: "Traffic-related delay in minutes"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1440

  - name: tbl_fact_vehicle_telemetry
    description: |
      Vehicle telemetry fact table containing sensor data:
      - Real-time vehicle performance metrics
      - Engine and fuel consumption data
      - Safety and efficiency indicators
    columns:
      - name: telemetry_id
        description: "Unique identifier for each telemetry record"
        tests:
          - unique
          - not_null
      - name: vehicle_id
        description: "Foreign key to vehicle dimension"
        tests:
          - not_null
          - relationships:
              to: ref('tbl_dim_vehicle')
              field: vehicle_id
      - name: timestamp
        description: "Timestamp of telemetry reading"
        tests:
          - not_null
      - name: speed_kmh
        description: "Vehicle speed in kilometers per hour"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 200
      - name: fuel_level_percent
        description: "Fuel level percentage"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      - name: engine_rpm
        description: "Engine RPM"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 8000
      - name: engine_temp_c
        description: "Engine temperature in Celsius"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: -40
              max_value: 150

  - name: tbl_fact_route_performance
    description: |
      Route performance fact table containing route analytics:
      - Route efficiency and performance metrics
      - Time and cost comparisons
      - Customer satisfaction scores
    columns:
      - name: route_id
        description: "Foreign key to route dimension"
        tests:
          - not_null
          - relationships:
              to: ref('tbl_dim_route')
              field: route_id
      - name: date_key
        description: "Foreign key to date dimension"
        tests:
          - not_null
          - relationships:
              to: ref('tbl_dim_date')
              field: date_key
      - name: actual_time_minutes
        description: "Actual travel time in minutes"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 2880
      - name: planned_time_minutes
        description: "Planned travel time in minutes"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 2880
      - name: time_variance_minutes
        description: "Time variance in minutes"
        tests:
          - dbt_utils.accepted_range:
              min_value: -1440
              max_value: 1440
      - name: traffic_delays_minutes
        description: "Traffic delays in minutes"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1440
      - name: weather_delays_minutes
        description: "Weather delays in minutes"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1440
      - name: customer_satisfaction_avg
        description: "Average customer satisfaction score"
        tests:
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 5

  - name: tbl_fact_route_conditions
    description: |
      Route conditions fact table containing environmental data:
      - Weather and traffic conditions
      - Impact scores and adjustments
    columns:
      - name: condition_id
        description: "Unique identifier for each condition record"
        tests:
          - unique
          - not_null
      - name: route_id
        description: "Foreign key to route dimension"
        tests:
          - not_null
          - relationships:
              to: ref('tbl_dim_route')
              field: route_id
      - name: date_key
        description: "Foreign key to date dimension"
        tests:
          - not_null
          - relationships:
              to: ref('tbl_dim_date')
              field: date_key

  - name: tbl_fact_vehicle_utilization
    description: |
      Vehicle utilization fact table containing fleet analytics:
      - Vehicle usage and efficiency metrics
      - Cost and performance indicators
    columns:
      - name: utilization_id
        description: "Unique identifier for each utilization record"
        tests:
          - unique
          - not_null
      - name: vehicle_id
        description: "Foreign key to vehicle dimension"
        tests:
          - not_null
          - relationships:
              to: ref('tbl_dim_vehicle')
              field: vehicle_id
      - name: date_key
        description: "Foreign key to date dimension"
        tests:
          - not_null
          - relationships:
              to: ref('tbl_dim_date')
              field: date_key
      - name: total_distance_km
        description: "Total distance traveled in kilometers"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 2000
      - name: total_runtime_hours
        description: "Total runtime in hours"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 24
      - name: capacity_utilized_percent
        description: "Capacity utilization percentage"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      - name: fuel_consumed_liters
        description: "Fuel consumed in liters"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1000
      - name: utilization_score
        description: "Overall utilization score"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      - name: efficiency_score
        description: "Efficiency score"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      - name: cost_per_km
        description: "Cost per kilometer"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 10
      - name: revenue_per_km
        description: "Revenue per kilometer"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 20