-- Create audit database and schema
CREATE DATABASE IF NOT EXISTS AUDIT_DB;
CREATE SCHEMA IF NOT EXISTS AUDIT_DB.AUDIT_LOGS;

-- Grant necessary permissions
GRANT USAGE ON DATABASE AUDIT_DB TO ROLE SYSADMIN;
GRANT USAGE ON SCHEMA AUDIT_DB.AUDIT_LOGS TO ROLE SYSADMIN;
GRANT CREATE TABLE ON SCHEMA AUDIT_DB.AUDIT_LOGS TO ROLE SYSADMIN;
