-- Data Classification and Sensitivity Labels
-- This script sets up data classification for the logistics analytics platform

-- Create data classification tags
CREATE OR REPLACE TAG DATA_CLASSIFICATION;

-- Set classification levels
ALTER TAG DATA_CLASSIFICATION SET ALLOWED_VALUES 'PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED';

-- Apply data classification to schemas
ALTER SCHEMA LOGISTICS_DW_PROD.RAW SET TAG DATA_CLASSIFICATION = 'CONFIDENTIAL';
ALTER SCHEMA LOGISTICS_DW_PROD.STAGING SET TAG DATA_CLASSIFICATION = 'INTERNAL';
ALTER SCHEMA LOGISTICS_DW_PROD.MARTS SET TAG DATA_CLASSIFICATION = 'INTERNAL';
ALTER SCHEMA LOGISTICS_DW_PROD.ANALYTICS SET TAG DATA_CLASSIFICATION = 'PUBLIC';

-- Create PII identification tag
CREATE OR REPLACE TAG PII_DATA;

-- Apply PII tags to sensitive columns
ALTER TABLE LOGISTICS_DW_PROD.RAW.CUSTOMERS 
  MODIFY COLUMN contact_email SET TAG PII_DATA = 'EMAIL';
ALTER TABLE LOGISTICS_DW_PROD.RAW.CUSTOMERS 
  MODIFY COLUMN contact_phone SET TAG PII_DATA = 'PHONE';
ALTER TABLE LOGISTICS_DW_PROD.RAW.CUSTOMERS 
  MODIFY COLUMN billing_address SET TAG PII_DATA = 'ADDRESS';

-- Create business sensitive data tag
CREATE OR REPLACE TAG BUSINESS_SENSITIVE;

-- Apply business sensitive tags
ALTER TABLE LOGISTICS_DW_PROD.MARTS.FACT_SHIPMENTS 
  MODIFY COLUMN revenue_usd SET TAG BUSINESS_SENSITIVE = 'FINANCIAL';
ALTER TABLE LOGISTICS_DW_PROD.MARTS.FACT_SHIPMENTS 
  MODIFY COLUMN total_cost_usd SET TAG BUSINESS_SENSITIVE = 'FINANCIAL';
ALTER TABLE LOGISTICS_DW_PROD.MARTS.FACT_SHIPMENTS 
  MODIFY COLUMN profit_margin_pct SET TAG BUSINESS_SENSITIVE = 'FINANCIAL';

-- Create data retention tag
CREATE OR REPLACE TAG DATA_RETENTION;

-- Set retention periods
ALTER TAG DATA_RETENTION SET ALLOWED_VALUES '1_YEAR', '3_YEARS', '7_YEARS', 'INDEFINITE';

-- Apply retention tags
ALTER TABLE LOGISTICS_DW_PROD.RAW.SHIPMENTS SET TAG DATA_RETENTION = '7_YEARS';
ALTER TABLE LOGISTICS_DW_PROD.RAW.CUSTOMERS SET TAG DATA_RETENTION = 'INDEFINITE';
ALTER TABLE LOGISTICS_DW_PROD.RAW.VEHICLES SET TAG DATA_RETENTION = 'INDEFINITE';
ALTER TABLE LOGISTICS_DW_PROD.RAW.MAINTENANCE SET TAG DATA_RETENTION = '7_YEARS';

-- Create compliance tags
CREATE OR REPLACE TAG COMPLIANCE_REQUIREMENT;

-- Set compliance requirements
ALTER TAG COMPLIANCE_REQUIREMENT SET ALLOWED_VALUES 'GDPR', 'CCPA', 'SOX', 'HIPAA', 'PCI_DSS', 'NONE';

-- Apply compliance tags
ALTER TABLE LOGISTICS_DW_PROD.RAW.CUSTOMERS SET TAG COMPLIANCE_REQUIREMENT = 'GDPR';
ALTER TABLE LOGISTICS_DW_PROD.MARTS.FACT_SHIPMENTS SET TAG COMPLIANCE_REQUIREMENT = 'SOX';

-- Create data lineage tag
CREATE OR REPLACE TAG DATA_LINEAGE;

-- Apply lineage tags to track data flow
ALTER TABLE LOGISTICS_DW_PROD.STAGING.STG_SHIPMENTS SET TAG DATA_LINEAGE = 'RAW_TO_STAGING';
ALTER TABLE LOGISTICS_DW_PROD.MARTS.FACT_SHIPMENTS SET TAG DATA_LINEAGE = 'STAGING_TO_MARTS';
ALTER TABLE LOGISTICS_DW_PROD.ANALYTICS.PERFORMANCE_DASHBOARD SET TAG DATA_LINEAGE = 'MARTS_TO_ANALYTICS';

-- Create data quality tag
CREATE OR REPLACE TAG DATA_QUALITY;

-- Set quality levels
ALTER TAG DATA_QUALITY SET ALLOWED_VALUES 'HIGH', 'MEDIUM', 'LOW', 'UNKNOWN';

-- Apply quality tags
ALTER TABLE LOGISTICS_DW_PROD.MARTS.FACT_SHIPMENTS SET TAG DATA_QUALITY = 'HIGH';
ALTER TABLE LOGISTICS_DW_PROD.MARTS.DIM_CUSTOMER SET TAG DATA_QUALITY = 'HIGH';
ALTER TABLE LOGISTICS_DW_PROD.RAW.WEATHER SET TAG DATA_QUALITY = 'MEDIUM';
ALTER TABLE LOGISTICS_DW_PROD.RAW.TRAFFIC SET TAG DATA_QUALITY = 'MEDIUM';

-- Create view to show data classification summary
CREATE OR REPLACE VIEW LOGISTICS_DW_PROD.ANALYTICS.V_DATA_CLASSIFICATION_SUMMARY AS
SELECT 
    table_catalog as database_name,
    table_schema as schema_name,
    table_name,
    column_name,
    data_type,
    GET_TAG('DATA_CLASSIFICATION', table_catalog, table_schema, table_name) as data_classification,
    GET_TAG('PII_DATA', table_catalog, table_schema, table_name, column_name) as pii_type,
    GET_TAG('BUSINESS_SENSITIVE', table_catalog, table_schema, table_name, column_name) as business_sensitivity,
    GET_TAG('DATA_RETENTION', table_catalog, table_schema, table_name) as retention_period,
    GET_TAG('COMPLIANCE_REQUIREMENT', table_catalog, table_schema, table_name) as compliance_requirement,
    GET_TAG('DATA_QUALITY', table_catalog, table_schema, table_name) as data_quality_level
FROM information_schema.columns
WHERE table_catalog = 'LOGISTICS_DW_PROD'
    AND table_schema IN ('RAW', 'STAGING', 'MARTS', 'ANALYTICS')
ORDER BY table_schema, table_name, column_name;

-- Grant access to data classification view
GRANT SELECT ON LOGISTICS_DW_PROD.ANALYTICS.V_DATA_CLASSIFICATION_SUMMARY TO ROLE DATA_STEWARD;
GRANT SELECT ON LOGISTICS_DW_PROD.ANALYTICS.V_DATA_CLASSIFICATION_SUMMARY TO ROLE DATA_ENGINEER;
